services:
  api:
    build:
      context: .
      dockerfile: src/HookSentry.Api/dockerfile
    ports:
      - "5143:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Your_database;Username=Your_username;Password=Your_password123
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Jwt__Key=YTNmOGMyZDFlNGI3MDkxZjZhNWQzZTJjOGYxYjRhNzA=
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=admin
      - RabbitMq__Password=123455
      - CredentialEncryption__Key=YTNmOGMyZDFlNGI3MDkxZjZhNWQzZTJjOGYxYjRhNzA=
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: src/HookSentry.Worker/dockerfile
    ports:
      - "7143:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Your_database;Username=Your_username;Password=Your_password123
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=admin
      - RabbitMq__Password=123455
      - CredentialEncryption__Key=YTNmOGMyZDFlNGI3MDkxZjZhNWQzZTJjOGYxYjRhNzA=
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123455"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Your_password123"
      POSTGRES_USER: "Your_username"
      POSTGRES_DB: "Your_database"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Your_username -d Your_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
