using HookSentry.Api.Common.Endpoints;
using HookSentry.Api.Common.Extensions;
using HookSentry.Api.Common.Validation;
using HookSentry.Domain;
using HookSentry.Domain.Security;
using HookSentry.Api.DataTransfer.Invites.Requests;
using HookSentry.Api.DataTransfer.Users.Responses;
using HookSentry.Domain.Invites;
using HookSentry.Domain.Users;
using HookSentry.Infrastructure.RateLimiting;

namespace HookSentry.Api.Features.Invites.RegisterWithInvite;

public class RegisterWithInviteEndpoint : IEndpoint
{
    public void MapEndpoints(IEndpointRouteBuilder app)
    {
        app.MapPost("/api/v1/invites/{token}/register", Handle)
            .WithName("RegisterWithInvite")
            .WithTags("Invites")
            .WithSummary("Registers a user using an invite link")
            .WithDescription("""
                Registers a new Developer user in the tenant associated with the invite.
                The invite is marked as used after successful registration.

                **No authentication required.**

                **Route parameters:**
                - `token` *(required)*: token generated by the admin when creating the invite

                **Body:**
                - `email` *(required)*: unique email address on the platform — max 255 characters
                - `password` *(required)*: plain text password — will be stored as hash

                **Return codes:**
                - `201 Created`: user created with Developer role
                - `400 Bad Request`: invalid data (malformed email, empty password)
                - `404 Not Found`: invite token not found
                - `409 Conflict`: invite already used or expired; or email already registered on the platform
                - `429 Too Many Requests`: more than 10 requests from the same IP within 1 hour
                """)
            .AllowAnonymous()
            .Produces<UserResponse>(StatusCodes.Status201Created)
            .Produces<string>(StatusCodes.Status400BadRequest)
            .Produces(StatusCodes.Status404NotFound)
            .Produces<string>(StatusCodes.Status409Conflict)
            .Produces(StatusCodes.Status429TooManyRequests);
    }

    private static async Task<IResult> Handle(
        string token,
        RegisterWithInviteRequest request,
        IPublicEndpointRateLimiter rateLimiter,
        HttpContext httpContext,
        IPasswordHasher passwordHasher,
        IInviteTokenRepository inviteRepository,
        IUserRepository userRepository,
        IUnitOfWorkFactory uowFactory,
        ILogger<RegisterWithInviteEndpoint> logger,
        CancellationToken ct)
    {
        var ip = httpContext.Connection.RemoteIpAddress?.ToString() ?? "unknown";

        if (await rateLimiter.IsBlockedAsync("register-with-invite", ip, ct))
            return Results.StatusCode(429);

        await rateLimiter.RecordAsync("register-with-invite", ip, ct);

        var invite = await inviteRepository.FindByTokenAsync(token, ct);

        if (invite is null)
            return Results.NotFound("Invite token not found.");

        if (InputSanitizer.ValidateEmail(request.Email) is { } emailErr)
            return Results.BadRequest(emailErr);

        var normalizedEmail = request.Email.Trim().ToLowerInvariant();

        if (await userRepository.EmailExistsAsync(normalizedEmail, ct))
            return Results.Conflict($"Email '{request.Email}' is already in use.");

        string passwordHash;
        try { passwordHash = passwordHasher.Hash(request.Password); }
        catch (ArgumentException ex) { return Results.BadRequest(ex.Message); }

        await using var uow = uowFactory.Create();

        try { invite.Use(); }
        catch (InvalidOperationException ex) { return Results.Conflict(ex.Message); }

        User newUser;
        try { newUser = new User(invite.TenantId, request.Email, passwordHash, invite.TargetRole); }
        catch (ArgumentException ex) { return Results.BadRequest(ex.Message); }

        await userRepository.AddAsync(newUser, ct);
        try
        {
            await uow.CommitAsync(ct);
        }
        catch (NHibernate.StaleObjectStateException)
        {
            return Results.Conflict("This invite has already been used.");
        }
        catch (Exception ex) when (ex.IsUniqueViolation())
        {
            return Results.Conflict($"Email '{request.Email}' is already in use.");
        }

        logger.LogInformation(
            "User registered via invite. TenantId={TenantId} UserId={UserId} Email={Email} InviteId={InviteId}",
            newUser.TenantId, newUser.Id, newUser.Email, invite.Id);

        return Results.Created($"/api/v1/users/{newUser.Id}", UserResponse.From(newUser));
    }
}
